---
# Repository-specific PipelineRun configuration
# Customize the parameters below for your specific repository
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: e2e-pipeline-run
spec:
  params:
    # Git repository configuration
    - name: branch-name
      value: btweed/e2e
    - name: repo-url
      value: https://github.com/RedHatInsights/learning-resources.git

    # Application artifact to test
    - name: SOURCE_ARTIFACT
      # Use latest prod image or specify a PR/dev image
      # value: quay.io/redhat-services-prod/hcc-platex-services-tenant/learning-resources:latest
      value: quay.io/redhat-user-workloads/hcc-platex-services-tenant/learning-resources/learning-resources:on-pr-c1a61630f80215241cf5ae39e2fd1d101de344ad

    # Test credentials (substituted from environment variables)
    - name: E2E_USER
      value: "${E2E_USER}"
    - name: E2E_PASSWORD
      value: "${E2E_PASSWORD}"
    - name: e2e_proxy
      value: "${E2E_PROXY_URL}"

    # Custom proxy routes for this application
    - name: proxy-routes-json
      value: |
        {
          "/index.html": {
            "url": "http://localhost:9912",
            "is_chrome": true
          },
          "/apps/chrome*": {
            "url": "http://localhost:9912",
            "is_chrome": true
          },
          "/apps/learning-resources*": {
            "url": "http://localhost:8000"
          },
          "/settings/learning-resources*": {
            "url": "http://localhost:8000"
          },
          "/openshift/learning-resources*":  {
            "url": "http://localhost:8000"
          },
          "/ansible/learning-resources*":  {
            "url": "http://localhost:8000"
          },
          "/insights/learning-resources*":  {
            "url": "http://localhost:8000"
          },
          "/edge/learning-resources*":  {
            "url": "http://localhost:8000"
          },
          "/iam/learning-resources*":  {
            "url": "http://localhost:8000"
          },
          "/learning-resources*":  {
            "url": "http://localhost:8000"
          },
          "/learning-resources/creator*": {
            "url": "http://localhost:8000"
          }
        }

    # Optional: Override the default test script
    # - name: e2e-tests-script
    #   value: |
    #     echo "Running custom test script"
    #     cd /workspace/output
    #     npm install
    #     npx playwright test playwright/*

  # Workspace configuration
  workspaces:
    - name: shared-code-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

  # Reference to the shared pipeline definition
  pipelineRef:
    name: e2e-pipeline

  # Task-specific runtime configuration
  taskRunSpecs:
    - pipelineTaskName: e2e-test-run
      podTemplate:
        # Override /etc/hosts to redirect stage.foo.redhat.com to localhost
        hostAliases:
          - ip: "127.0.0.1"
            hostnames:
              - "stage.foo.redhat.com"
