---
# Repository-specific PipelineRun configuration
# Customize the parameters below for your specific repository
apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: e2e-pipeline-run
spec:
  params:
    # Git repository configuration
    - name: branch-name
      value: btweed/e2e
    - name: repo-url
      value: https://github.com/RedHatInsights/learning-resources.git

    # Application artifact to test
    - name: SOURCE_ARTIFACT
      # Use latest prod image or specify a PR/dev image
      value: quay.io/redhat-services-prod/hcc-platex-services-tenant/learning-resources:latest
      # value: quay.io/redhat-user-workloads/hcc-platex-services-tenant/learning-resources/learning-resources:on-pr-c1a61630f80215241cf5ae39e2fd1d101de344ad

    # Test credentials (substituted from environment variables)
    - name: E2E_USER
      value: "${E2E_USER}"
    - name: E2E_PASSWORD
      value: "${E2E_PASSWORD}"
    - name: e2e_proxy
      value: "${E2E_PROXY_URL}"
    - name: STAGE_ACTUAL_HOSTNAME
      value: "${STAGE_ACTUAL_HOSTNAME}"
    - name: HCC_ENV_URL
      value: "${HCC_ENV_URL}"
    - name: HCC_ENV
      value: "stage"

    # Caddy configuration for the test application (loaded from caddy_config/app_config)
    - name: app-caddy-config
      value: "${APP_CADDY_CONFIG}"

    # Custom proxy routes for this application (loaded from caddy_config/proxy_config)
    - name: proxy-routes
      value: "${PROXY_ROUTES}"

    # Optional: Override the default test script
    # - name: e2e-tests-script
    #   value: |
    #     echo "Running custom test script"
    #     cd /workspace/output
    #     npm install
    #     npx playwright test playwright/*

  # Workspace configuration
  workspaces:
    - name: shared-code-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi

  # Reference to the shared pipeline definition
  pipelineRef:
    name: e2e-pipeline

  # Task-specific runtime configuration
  taskRunSpecs:
    - pipelineTaskName: e2e-test-run
      podTemplate:
        # Override /etc/hosts to redirect stage.foo.redhat.com to localhost
        hostAliases:
          - ip: "::1"
            hostnames:
              - "stage.foo.redhat.com"
          - ip: "127.0.0.1"
            hostnames:
              - "stage.foo.redhat.com"
