---
# ConfigMap for Caddy configuration - serves chrome UI static assets
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrome-dev-caddyfile
data:
  Caddyfile: |
    {
      debug
    }

    :9912 {
        root * /opt/app-root/src/build/stable

        # Handle /apps/chrome* requests - strip prefix and serve
        @app_match {
            path /apps/chrome*
        }
        handle @app_match {
            uri strip_prefix /apps/chrome
            file_server {
                browse
            }
        }

        # Handle all other requests - serve files normally
        handle {
            file_server
        }

        header {
            Cache-Control "no-cache, no-store, must-revalidate"
            Pragma "no-cache"
            Expires "0"
        }
        header {
            Access-Control-Allow-Origin "*"
            Access-Control-Allow-Methods "GET, POST, OPTIONS"
            Access-Control-Allow-Headers "Content-Type"
        }
    }
---
# Shared E2E Task definition
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: e2e-task
spec:
  params:
    - description: The Trusted Artifact URI containing the application to test
      name: SOURCE_ARTIFACT
      type: string
    - description: The script to execute the e2e tests
      name: e2e-tests-script
      type: string
    - description: HTTP proxy configuration
      name: HTTP_PROXY
      type: string
    - description: Test user credentials
      name: E2E_USER
      type: string
    - description: Test user password
      name: E2E_PASSWORD
      type: string
    - description: Proxy routes configuration (Caddy directives)
      name: PROXY_ROUTES_JSON
      type: string
      default: |
        handle /index.html {
            reverse_proxy http://localhost:9912
        }

        handle /apps/chrome* {
            reverse_proxy http://localhost:9912
        }
    - description: Application port (default 8000)
      name: APP_PORT
      type: string
      default: "8000"
    - description: Playwright image to use for testing
      name: PLAYWRIGHT_IMAGE
      type: string
      default: "quay.io/btweed/playwright_e2e:latest"
    - description: Chrome dev image
      name: CHROME_DEV_IMAGE
      type: string
      default: "quay.io/redhat-services-prod/hcc-platex-services-tenant/insights-chrome-dev:latest"
    - description: Frontend proxy image
      name: PROXY_IMAGE
      type: string
      default: "quay.io/redhat-user-workloads/hcc-platex-services-tenant/frontend-development-proxy:latest"
    - description: Actual stage environment hostname (for catch-all proxy)
      name: STAGE_ACTUAL_HOSTNAME
      type: string
  sidecars:
    - image: $(params.PROXY_IMAGE)
      name: frontend-dev-proxy
      command: ["/bin/sh", "-c"]
      args:
        - |
          #!/bin/sh
          echo "Waiting for /config/routes to be available..."
          timeout=60
          elapsed=0
          while [ ! -f /config/routes ] && [ $elapsed -lt $timeout ]; do
            echo "Config file not found, waiting... ($elapsed/$timeout seconds)"
            sleep 2
            elapsed=$((elapsed + 2))
          done

          if [ ! -f /config/routes ]; then
            echo "ERROR: /config/routes not found after ${timeout} seconds"
            exit 1
          fi

          echo "Config file found!"
          echo "Routes content:"
          cat /config/routes

          # Export LOCAL_ROUTES environment variable from the file
          export LOCAL_ROUTES="$(cat /config/routes)"
          echo "LOCAL_ROUTES environment variable set"

          # Check if Caddyfile exists and contains {$LOCAL_ROUTES} placeholder
          echo "Checking for {$LOCAL_ROUTES} placeholder in Caddyfile..."
          if [ ! -f /etc/caddy/Caddyfile ]; then
            echo "ERROR: /etc/caddy/Caddyfile not found!"
            exit 1
          fi

          echo "Original Caddyfile:"
          cat /etc/caddy/Caddyfile

          if ! grep -q '{$LOCAL_ROUTES}' /etc/caddy/Caddyfile; then
            echo "ERROR: {$LOCAL_ROUTES} placeholder not found in Caddyfile!"
            echo "The Caddyfile must contain {$LOCAL_ROUTES} where routes should be injected."
            exit 1
          fi

          echo "Found {$LOCAL_ROUTES} placeholder, performing manual substitution..."

          # Check for required tools
          echo "Checking for required tools..."
          for tool in awk sed grep cat; do
            if ! command -v $tool >/dev/null 2>&1; then
              echo "ERROR: Required tool '$tool' not found in container!"
              exit 1
            fi
          done
          echo "All required tools available"

          # Manually substitute all environment variables in the Caddyfile
          # This gives us full visibility of the final config before Caddy starts

          # Read the routes and properly indent them (4 spaces to match Caddyfile indentation)
          sed 's/^/    /' /config/routes > /tmp/routes_indented.txt

          # Substitute {$LOCAL_ROUTES} with actual routes, and other env vars
          awk -v hcc_env="$HCC_ENV" -v proxy_port="$PROXY_PORT" -v hcc_env_url="$HCC_ENV_URL" '
          BEGIN {
            while ((getline line < "/tmp/routes_indented.txt") > 0) {
              routes = routes line "\n"
            }
            close("/tmp/routes_indented.txt")
            # Remove trailing newline
            sub(/\n$/, "", routes)
          }
          {
            line = $0
            # Replace {$LOCAL_ROUTES}
            if (line ~ /\{\$LOCAL_ROUTES\}/) {
              print routes
            } else {
              # Replace other environment variables
              gsub(/\{\$HCC_ENV\}/, hcc_env, line)
              gsub(/\{\$PROXY_PORT\}/, proxy_port, line)
              gsub(/\{\$HCC_ENV_URL\}/, hcc_env_url, line)
              print line
            }
          }
          ' /etc/caddy/Caddyfile > /tmp/Caddyfile.new

          mv /tmp/Caddyfile.new /etc/caddy/Caddyfile

          # Enable debug logging and admin API
          echo "Enabling debug mode and admin API..."

          # Change 'admin off' to 'admin :2019' to enable admin API
          sed -i 's/admin off/admin :2019/g' /etc/caddy/Caddyfile

          # Add debug to global options block if not already present
          if ! grep -q "debug" /etc/caddy/Caddyfile; then
            # Insert 'debug' after the first opening brace
            sed -i '1,/^{/s/^{/{\n debug/' /etc/caddy/Caddyfile
          fi

          # Replace stage.foo.redhat.com in catch-all handler with actual stage hostname
          echo "Configuring catch-all handler to use actual stage environment..."
          if [ -n "$STAGE_ACTUAL_HOSTNAME" ]; then
            echo "Replacing stage.foo.redhat.com with ${STAGE_ACTUAL_HOSTNAME} in catch-all handler"
            sed -i "s|https://stage\.foo\.redhat\.com|https://${STAGE_ACTUAL_HOSTNAME}|g" /etc/caddy/Caddyfile
          else
            echo "WARNING: STAGE_ACTUAL_HOSTNAME not set, catch-all will use stage.foo.redhat.com (may fail due to hostAliases)"
          fi

          # fix formatting of Caddyfile
          caddy fmt --overwrite /etc/caddy/Caddyfile

          echo "Final Caddyfile (after LOCAL_ROUTES substitution):"
          cat /etc/caddy/Caddyfile

          # Wait for insights-chrome-dev to be ready on port 9912
          echo "Waiting for insights-chrome-dev to be ready on port 9912..."
          max_wait=60
          elapsed=0
          while [ $elapsed -lt $max_wait ]; do
            if wget -q -O /dev/null --timeout=2 http://127.0.0.1:9912 2>/dev/null; then
              echo "insights-chrome-dev is ready!"
              break
            fi
            echo "Waiting for insights-chrome-dev... ($elapsed/$max_wait seconds)"
            sleep 2
            elapsed=$((elapsed + 2))
          done

          if [ $elapsed -ge $max_wait ]; then
            echo "ERROR: insights-chrome-dev did not become ready after ${max_wait} seconds"
            exit 1
          fi

          # Wait for run-application to be ready on port 8000
          echo "Waiting for run-application to be ready on port 8000..."
          elapsed=0
          while [ $elapsed -lt $max_wait ]; do
            if wget -q -O /dev/null --timeout=2 http://127.0.0.1:8000 2>/dev/null; then
              echo "run-application is ready!"
              break
            fi
            echo "Waiting for run-application... ($elapsed/$max_wait seconds)"
            sleep 2
            elapsed=$((elapsed + 2))
          done

          if [ $elapsed -ge $max_wait ]; then
            echo "WARNING: run-application did not become ready after ${max_wait} seconds"
            exit 1
          fi

          echo "Starting frontend-development-proxy..."
          caddy run --config /etc/caddy/Caddyfile
      env:
        - name: HTTP_PROXY
          value: $(params.HTTP_PROXY)
        - name: HTTPS_PROXY
          value: $(params.HTTP_PROXY)
        - name: HCC_ENV
          value: "stage"
        - name: PROXY_PORT
          value: "1337"
        - name: HCC_ENV_URL
          value: "https://stage.foo.redhat.com"
        - name: STAGE_ACTUAL_HOSTNAME
          value: $(params.STAGE_ACTUAL_HOSTNAME)
      securityContext:
        privileged: false
      volumeMounts:
        - name: proxy-config
          mountPath: /config
    - image: $(params.CHROME_DEV_IMAGE)
      name: insights-chrome-dev
      command: ["caddy"]
      args: ["run", "--config", "/etc/caddy/Caddyfile"]
      securityContext:
        privileged: false
      volumeMounts:
        - name: workdir
          mountPath: /var/workdir
        - name: chrome-dev-caddyfile
          mountPath: /etc/caddy/Caddyfile
          subPath: Caddyfile
    - name: run-application
      image: $(params.SOURCE_ARTIFACT)
      securityContext:
        privileged: false
      volumeMounts:
        - name: workdir
          mountPath: /var/workdir
  volumes:
    - name: workdir
      emptyDir: {}
    - name: proxy-config
      emptyDir: {}
    - name: chrome-dev-caddyfile
      configMap:
        name: chrome-dev-caddyfile
  stepTemplate:
    volumeMounts:
      - mountPath: /var/workdir
        name: workdir
        readOnly: false
  steps:
    - name: setup-proxy-routes
      image: quay.io/quay/busybox
      script: |
        #!/bin/sh
        set -e
        echo "Writing proxy routes configuration (Caddy directives)..."
        cat > /config/routes << 'EOF'
        $(params.PROXY_ROUTES_JSON)
        EOF
        chmod 644 /config/routes
        echo "Proxy routes configured successfully:"
        cat /config/routes
      volumeMounts:
        - name: proxy-config
          mountPath: /config
    - image: $(params.PLAYWRIGHT_IMAGE)
      env:
        - name: HTTP_PROXY
          value: $(params.HTTP_PROXY)
        - name: HTTPS_PROXY
          value: $(params.HTTP_PROXY)
        - name: E2E_USER
          value: $(params.E2E_USER)
        - name: E2E_PASSWORD
          value: $(params.E2E_PASSWORD)
        - name: NO_PROXY
          value: "stage.foo.redhat.com"
      name: e2e-tests
      computeResources:
        requests:
          cpu: "2000m"
          memory: "4Gi"
        limits:
          cpu: "4000m"
          memory: "8Gi"
      securityContext:
        runAsUser: 0
      script: $(params.e2e-tests-script)
  workspaces:
    - name: shared-code-workspace
      mountPath: /workspace/output
---
# Shared E2E Pipeline definition
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: e2e-pipeline
spec:
  params:
    - name: branch-name
      type: string
      description: Branch within the source repository
    - name: repo-url
      type: string
      description: URL of the source repository
    - name: SOURCE_ARTIFACT
      description: URI of the trusted artifact containing the built application
    - name: e2e_proxy
      description: HTTP proxy for external requests
    - name: E2E_USER
      description: Test automation username
    - name: E2E_PASSWORD
      description: Test automation password
    - name: STAGE_ACTUAL_HOSTNAME
      type: string
      description: Actual stage environment hostname (for catch-all proxy)
    - name: proxy-routes-json
      type: string
      description: Custom proxy routes configuration (Caddy directives)
      default: |
        handle /index.html {
            reverse_proxy http://localhost:9912
        }

        handle /apps/chrome* {
            reverse_proxy http://localhost:9912
        }
    - name: e2e-tests-script
      type: string
      description: Custom test execution script
      default: |
        # TODO: Wait for stage.foo.redhat.com to be responsive
        set -x
        echo "HTTP_PROXY is ${HTTP_PROXY}"
        echo "HTTPS_PROXY is ${HTTPS_PROXY}"
        getent hosts stage.foo.redhat.com
        cd /workspace/output
        set -e
        sleep 2000
        npm install
        npx playwright test
  workspaces:
    - name: shared-code-workspace
      description: Workspace for passing repo source to the test run task
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-code-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
    - name: e2e-test-run
      taskRef:
        name: e2e-task
      workspaces:
        - name: shared-code-workspace
          workspace: shared-code-workspace
      runAfter:
        - fetch-source
      params:
        - name: SOURCE_ARTIFACT
          value: $(params.SOURCE_ARTIFACT)
        - name: HTTP_PROXY
          value: $(params.e2e_proxy)
        - name: E2E_USER
          value: $(params.E2E_USER)
        - name: E2E_PASSWORD
          value: $(params.E2E_PASSWORD)
        - name: STAGE_ACTUAL_HOSTNAME
          value: $(params.STAGE_ACTUAL_HOSTNAME)
        - name: PROXY_ROUTES_JSON
          value: $(params.proxy-routes-json)
        - name: e2e-tests-script
          value: $(params.e2e-tests-script)
